name: real_estate
description: "A Flutter Portfolio - Assessment Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1


  go_router: ^14.2.1
  intl: any
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.3.5
  very_good_analysis: ^6.0.0


dev_dependencies:
  build_runner: ^2.4.11

  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0 #Will update after analyzer gets update
  riverpod_lint: ^2.3.10 #Will update after analyzer gets update


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/



  fonts:
    - family: GothamSSm
      fonts:
        - asset: assets/fonts/GothamSSm-Bold.otf
        - asset: assets/fonts/GothamSSm-Book.otf
        - asset: assets/fonts/GothamSSm-Light.otf
        - asset: assets/fonts/GothamSSm-Medium.otf

